from enum import Enum

class MaintenanceCategory(Enum):
    ENGINE_OIL_AND_FILTER = "Engine oil and filter"
    TRANSMISSION_OIL = "Transmission oil"
    AUTOMATIC_TRANSMISSION_FLUID = "Automatic transmission fluid"
    CVT_FLUID = "CVT fluid"
    DCT_FLUID = "DCT fluid"
    DIFFERENTIAL_OIL = "Differential oil"
    TRANSFER_CASE_OIL = "Transfer case oil"
    COOLANT = "Coolant"
    BRAKE_FLUID = "Brake fluid"
    POWER_STEERING_FLUID = "Power steering fluid"
    AIR_FILTER = "Air filter"
    CABIN_FILTER = "Cabin filter"
    FUEL_FILTER = "Fuel filter"
    TIMING_BELT = "Timing belt"
    ACCESSORY_DRIVE_BELT = "Accessory drive belt"
    SPARK_PLUGS = "Spark plugs"
    TIRES = "Tires"
    WIPER_BLADES = "Wiper blades"